import { Navigation } from "@/components/navigation";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Users, Target, Lightbulb, Award } from "lucide-react";
import Link from "next/link";

export default function Artworks() {
  // Create array of numbers 1-20 and shuffle them
  const shuffleArray = (array: number[]) => {
    const shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
  };

  const imageNumbers = shuffleArray(
    Array.from({ length: 20 }, (_, i) => i + 1)
  );

  return (
    <div className="min-h-screen bg-white">
      <Navigation />

      {/* Hero Section */}
      <section className="pt-24 pb-4 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <Link
            href="/"
            className="inline-flex items-center text-gray-600 hover:text-black transition-colors duration-200 mb-8"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Home
          </Link>

          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-black leading-tight mb-8">
            Artworks
          </h1>

          <p className="text-xl text-gray-600 leading-relaxed">
            Discover artworks generated by various people using our
            installation. Take a look at the creativity and innovation that has
            emerged from our community.
          </p>
        </div>
      </section>

      {/* Image grid aspect ratio 1/1 */}
      <section className="py-8 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
          {imageNumbers.map((imageNumber, index) => (
            <div
              key={index}
              className="aspect-square bg-gray-200 rounded-lg overflow-hidden"
            >
              <img
                src={`https://cdn.jsdelivr.net/gh/projektmodul-ki/static/example-artworks/Example_${imageNumber}.png`}
                alt={`Interactive artwork ${imageNumber}`}
                className="w-full h-full object-cover"
              />
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
